### ISSUE TITLE
Link for nested comment doesn't work without ssr.

### ISSUE THREAD

**Issue by 7c1** [teejayclub/teejay.club#108]
When user clicks the link on right sidebar if the comment is not in the first batch request it will not be displayed. If user opens the link in a new window ssr creates whole tree.

**Comment by teejayadmin** [comment]
Да, заметил этот баг. Скорее всего в useQuery надо инвалидацию кэша сделать, но не точно.

**Comment by 7c1** [comment]
note: if it has already been loaded, it will be shown

**Comment by 7c1** [comment]
> Да, заметил этот баг. Скорее всего в useQuery надо инвалидацию кэша сделать, но не точно.

just to keep track of this.

**Comment by teejayadmin** [comment]
SSR для комментов не работает, кстати. Они только на client side.

**Comment by teejayadmin** [comment]
Исправил.
