### ISSUE TITLE
не переходит к комменту при клике на него из ленты коментов

### ISSUE THREAD

**Issue by f242** [teejayclub/teejay.club#92]
вот вижу комент
![image](https://user-images.githubusercontent.com/10371194/190909416-d7b3ba89-11c0-450d-9aac-fd5a60568189.png)
ссылка https://teejay.club/posts/421#comments/1247
жму и просто открывается пост, а к коменту не переходит

**Comment by teejayadmin** [comment]
Уже есть: #88
