### ISSUE TITLE
Добавить ограничения в зависимости от хэша IP адреса

### ISSUE THREAD

**Issue by teejayadmin** [teejayclub/teejay.club#96]
Хранить хэши IP адресов, чтобы ограничить по времени количество регистраций на один IP. Для безопасности нужно придумать схему, где хэш IP адреса невозможно будет связать с пользователем.

**Comment by teejayadmin** [comment]
Пока на обсуждении и обдумывании. Может быть, можно будет обойтись без этого.

**Comment by d3spairx** [comment]
А зачем хэшировать IP-адрес? И что это значит:

**Comment by teejayadmin** [comment]
В дискорде обсуждали эту задачу. Решил от неё отказаться. Регистрацию буду ограничивать другими способами.
